name: pull-request-test

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-20.04
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.fork == true }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Check if Dockerfile is building
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: false
