name: pull-request-test

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-20.04
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.fork == true }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Check if Dockerfile is building
              uses: docker/build-push-action@v3
              with:
                  context: .
                  tags: "waf-proxy"
                  push: false

            - name: Test image
              run: "make test IMAGE=waf-proxy"

            - name: Scan image
              uses: aquasecurity/trivy-action@0.8.0
              with:
                  image-ref: "ghcr.io/riotkit-org/waf-proxy:${{ steps.tag.outputs.TAG }}"
                  format: 'table'
